postgres:
  restart: always
  image: postgres:10.1
  ports:
    - '9119:9119'
  environment:
    POSTGRES_USER: 'ldd_user'
    POSTGRES_PASSWORD: 'pass'
  volumes:
    - /home/vdineshc/UDL/pipelines/dbserve/init:/docker-entrypoint-initdb.d/
